openapi: "3.0.1"
info:
  title: "Queue Based Leveling Example"
  version: "2021-03-31 17:32:29UTC"
paths:
  ############################################
  # Path has no query string parameters
  ############################################
  /twilio-webhook:
    post:
      responses:
        default:
          description: "Response for POST /"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        integrationSubtype: "SQS-SendMessage"
        credentials:
          Fn::GetAtt: [TwilioMessagingWebhookApiRole, Arn]
        connectionType: "INTERNET"
        payloadFormatVersion: "1.0"
        requestParameters:
          MessageBody: "$request.body"
          MessageAttributes: >-
            {
              "x-twilio-signature": {
                "DataType": "String",
                "StringValue": "${request.header.x-twilio-signature}"
              },
              "sourceIp": {
                "DataType": "String",
                "StringValue": "${context.identity.sourceIp}"
              }    
              ,
              "domainName": {
                "DataType": "String",
                "StringValue": "${context.domainName}"
              }                     
              ,
              "path": {
                "DataType": "String",
                "StringValue": "${context.path}"
              }   
              ,
              "queryStringParams": {
                "DataType": "String",
                "StringValue": "no"
              }                                   
                                                 
            }          
          QueueUrl:
            Ref: TwilioMessagingWebhookQueue


x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"